{START_FORM}
<fieldset><legend><strong>{SETTINGS_LABEL}</strong></legend>
<p>{CHANNEL_LIMIT} {CHANNEL_LIMIT_LABEL}</p>
<p>{CACHE_TIMEOUT} {CACHE_TIMEOUT_LABEL}</p>
<p>{REQ_APPROVAL} {REQ_APPROVAL_LABEL}</p>
<p>{SHOW_BLOCK} {SHOW_BLOCK_LABEL} -
{BLOCK_ORDER_BY_RAND_1}{BLOCK_ORDER_BY_RAND_1_LABEL}
{BLOCK_ORDER_BY_RAND_2}{BLOCK_ORDER_BY_RAND_2_LABEL} -
{BLOCK_ON_HOME_ONLY} {BLOCK_ON_HOME_ONLY_LABEL}</p>
<p>{EDITOR} {EDITOR_LABEL}</p>
<p>{WEBMASTER} {WEBMASTER_LABEL}</p>
<p>{COPYRIGHT} {COPYRIGHT_LABEL}</p>
<p>{RM_MEDIA} {RM_MEDIA_LABEL}</p>
</fieldset>
<fieldset><legend><strong>{IMAGE_LABEL}</strong></legend>
<p>{MAX_WIDTH} {MAX_WIDTH_LABEL}</p>
<p>{MAX_HEIGHT} {MAX_HEIGHT_LABEL}</p>
<p>{MOD_FOLDERS_ONLY} {MOD_FOLDERS_ONLY_LABEL}</p>
</fieldset>
{SAVE} {END_FORM}
