{START_FORM}
<fieldset>
    <legend><strong>{SETTINGS_GROUP_LABEL}</strong></legend>
    <p>{MODULE_TITLE} {MODULE_TITLE_LABEL}</p>
    <p>{ALLOW_ANON} {ALLOW_ANON_LABEL}</p>
    <p>{SORTBY_TITLE} {SORTBY_1}{SORTBY_1_LABEL} {SORTBY_2}{SORTBY_2_LABEL}</p>
    <p>{REQ_APPROVAL} {REQ_APPROVAL_LABEL}</p>
    <p>{SEND_NOTIFICATION} {SEND_NOTIFICATION_LABEL}</p>
    <p>{NOTIFY_ALL_SAVES} {NOTIFY_ALL_SAVES_LABEL}</p>
    <p>{ADMIN_CONTACT} {ADMIN_CONTACT_LABEL}</p>
    <p>{SHOW_BLOCK} {SHOW_BLOCK_LABEL} - {BLOCK_ORDER_BY_RAND_1}{BLOCK_ORDER_BY_RAND_1_LABEL} {BLOCK_ORDER_BY_RAND_2}{BLOCK_ORDER_BY_RAND_2_LABEL} - {BLOCK_ON_HOME_ONLY} {BLOCK_ON_HOME_ONLY_LABEL}</p>
    <p>{ENABLE_EXPIRY} {ENABLE_EXPIRY_LABEL} - {EXPIRY_INTERVAL} {EXPIRY_INTERVAL_LABEL}</p>
    <p>{USE_CAPTCHA} {USE_CAPTCHA_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{OPTIONS_GROUP_LABEL}</strong></legend>
    <p>{USE_CATEGORIES} {USE_CATEGORIES_LABEL}</p>
    <p>{USE_LOCATIONS} {USE_LOCATIONS_LABEL}</p>
    <p>{USE_FEATURES} {USE_FEATURES_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{COMMENTS_GROUP_LABEL}</strong></legend>
    <p>{COMMENTS_ENABLE} {COMMENTS_ENABLE_LABEL}</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{COMMENTS_ENFORCE} {COMMENTS_ENFORCE_LABEL}</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{COMMENTS_ANON_ENABLE} {COMMENTS_ANON_ENABLE_LABEL}</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{COMMENTS_ANON_ENFORCE} {COMMENTS_ANON_ENFORCE_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{PRIVACY_GROUP_LABEL}</strong></legend>
    <p>{PRIVACY_CONTACT_TITLE} - {PRIVACY_CONTACT_1}{PRIVACY_CONTACT_1_LABEL} {PRIVACY_CONTACT_2}{PRIVACY_CONTACT_2_LABEL} {PRIVACY_CONTACT_3}{PRIVACY_CONTACT_3_LABEL}</p>
    <p>{CONTACT_TYPE_TITLE} - {CONTACT_TYPE_1}{CONTACT_TYPE_1_LABEL} {CONTACT_TYPE_2}{CONTACT_TYPE_2_LABEL}</p>
    <p>{PRIVACY_WEB_TITLE} - {PRIVACY_WEB_1}{PRIVACY_WEB_1_LABEL} {PRIVACY_WEB_2}{PRIVACY_WEB_2_LABEL} {PRIVACY_WEB_3}{PRIVACY_WEB_3_LABEL}</p>
    <p>{PRIVACY_HOME_PHONE_TITLE} - {PRIVACY_HOME_PHONE_1}{PRIVACY_HOME_PHONE_1_LABEL} {PRIVACY_HOME_PHONE_2}{PRIVACY_HOME_PHONE_2_LABEL} {PRIVACY_HOME_PHONE_3}{PRIVACY_HOME_PHONE_3_LABEL}</p>
    <p>{PRIVACY_BUS_PHONE_TITLE} - {PRIVACY_BUS_PHONE_1}{PRIVACY_BUS_PHONE_1_LABEL} {PRIVACY_BUS_PHONE_2}{PRIVACY_BUS_PHONE_2_LABEL} {PRIVACY_BUS_PHONE_3}{PRIVACY_BUS_PHONE_3_LABEL}</p>
    <p>{PRIVACY_HOME_TITLE} - {PRIVACY_HOME_1}{PRIVACY_HOME_1_LABEL} {PRIVACY_HOME_2}{PRIVACY_HOME_2_LABEL} {PRIVACY_HOME_3}{PRIVACY_HOME_3_LABEL}</p>
    <p>{PRIVACY_BUSINESS_TITLE} - {PRIVACY_BUSINESS_1}{PRIVACY_BUSINESS_1_LABEL} {PRIVACY_BUSINESS_2}{PRIVACY_BUSINESS_2_LABEL} {PRIVACY_BUSINESS_3}{PRIVACY_BUSINESS_3_LABEL}</p>
    <p>{PRIVACY_EXPORT_TITLE} - {PRIVACY_EXPORT_1}{PRIVACY_EXPORT_1_LABEL} {PRIVACY_EXPORT_2}{PRIVACY_EXPORT_2_LABEL} {PRIVACY_EXPORT_3}{PRIVACY_EXPORT_3_LABEL}</p>
    <p>{PRIVACY_USE_SEARCH_TITLE} - {PRIVACY_USE_SEARCH_1}{PRIVACY_USE_SEARCH_1_LABEL} {PRIVACY_USE_SEARCH_2}{PRIVACY_USE_SEARCH_2_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{LIST_GROUP_LABEL}</strong></legend>
    <div class="smaller">{LIST_SETTINGS_TIP}</div>
    <p>{LIST_ADDRESS_TITLE} - {LIST_ADDRESS_1}{LIST_ADDRESS_1_LABEL} {LIST_ADDRESS_2}{LIST_ADDRESS_2_LABEL} {LIST_ADDRESS_3}{LIST_ADDRESS_3_LABEL} {LIST_ADDRESS_4}{LIST_ADDRESS_4_LABEL}</p>
    <p>{LIST_PHONE} {LIST_PHONE_LABEL}</p>
    <p>{LIST_CATEGORIES} {LIST_CATEGORIES_LABEL}</p>
    <p>{LIST_LOCATIONS} {LIST_LOCATIONS_LABEL}</p>
    <p>{LIST_FEATURES} {LIST_FEATURES_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{IMAGE_GROUP_LABEL}</strong></legend>
    <p>{MAX_IMG_WIDTH} {MAX_IMG_WIDTH_LABEL}</p>
    <p>{MAX_IMG_HEIGHT} {MAX_IMG_HEIGHT_LABEL}</p>
    <p>{MAX_THUMB_WIDTH} {MAX_THUMB_WIDTH_LABEL}</p>
    <p>{MAX_THUMB_HEIGHT} {MAX_THUMB_HEIGHT_LABEL}</p>
    <p>{OTHER_IMG_WIDTH} {OTHER_IMG_WIDTH_LABEL}</p>
    <p>{OTHER_IMG_HEIGHT} {OTHER_IMG_HEIGHT_LABEL}</p>
</fieldset>
<fieldset>
    <legend><strong>{FIELDS_GROUP_LABEL}</strong></legend>
    <div class="smaller">{FIELDS_NOTE}</div>
    <p class="smaller">{FIELDS_LIST_LABEL}</p>
    <p>{CUSTOM1_LIST} {CUSTOM1_NAME} {CUSTOM1_NAME_LABEL}</p>
    <p>{CUSTOM2_LIST} {CUSTOM2_NAME} {CUSTOM2_NAME_LABEL}</p>
    <p>{CUSTOM3_LIST} {CUSTOM3_NAME} {CUSTOM3_NAME_LABEL}</p>
    <p>{CUSTOM4_LIST} {CUSTOM4_NAME} {CUSTOM4_NAME_LABEL}</p>
    <p>{CUSTOM5_LIST} {CUSTOM5_NAME} {CUSTOM5_NAME_LABEL}</p>
    <p>{CUSTOM6_LIST} {CUSTOM6_NAME} {CUSTOM6_NAME_LABEL}</p>
    <p>{CUSTOM7_LIST} {CUSTOM7_NAME} {CUSTOM7_NAME_LABEL}</p>
    <p>{CUSTOM8_LIST} {CUSTOM8_NAME} {CUSTOM8_NAME_LABEL}</p>
</fieldset>
{SAVE}
{END_FORM}
