{START_FORM}
<fieldset><legend>{DB_LEGEND}</legend> {PLUG}
<table class="form-table">
    <tr>
        <td>{CREATEDB_LABEL}</td>
        <td>{CREATEDB}</td>
    </tr>
    <tr>
        <td>{DBTYPE_LABEL}</td>
        <td>{DBTYPE}</td>
    </tr>
    <tr>
        <td>{DBNAME_LABEL}</td>
        <td>{DBNAME}</td>
    </tr>
    <tr>
        <td>{DBUSER_LABEL}</td>
        <td>{DBUSER}</td>
    </tr>
    <tr>
        <td>{DBPASS_LABEL}</td>
        <td>{DBPASS}</td>
    </tr>
    <tr>
        <td>{DBPREFIX_LABEL}</td>
        <td>{DBPREFIX}</td>
    </tr>
    <tr>
        <td>{DBHOST_LABEL}</td>
        <td>{DBHOST}</td>
    </tr>
    <tr>
        <td>{DBPORT_LABEL}</td>
        <td>{DBPORT}</td>
    </tr>
</table>
{SUBMIT}</fieldset>
{END_FORM}
