{START_FORM}
<fieldset><legend>{BRANCH_LEGEND}</legend>
<table class="form-table">
    <tr>
        <td>{BRANCH_NAME_LABEL}</td>
        <td>{BRANCH_NAME}</td>
    </tr>
    <tr>
        <td>{DIRECTORY_LABEL}</td>
        <td>{DIRECTORY}</td>
    </tr>
    <tr>
        <td>{URL_LABEL}</td>
        <td>{URL}</td>
    </tr>
    <tr>
        <td>{SITE_HASH_LABEL}</td>
        <td>{SITE_HASH}</td>
    </tr>
</table>
{SUBMIT}</fieldset>
{END_FORM}
