{START_FORM}
<fieldset>
    <legend><strong>{SETTINGS_LABEL}</strong></legend>
    <p>{ENABLE_SIDEBOX} {ENABLE_SIDEBOX_LABEL}</p>
    <p>{SIDEBOX_HOMEONLY} {SIDEBOX_HOMEONLY_LABEL}</p>
    <p>{SIDEBOX_TEXT} {SIDEBOX_TEXT_LABEL}</p>
    <p>{ENABLE_FILES} {ENABLE_FILES_LABEL}</p>
    <p>{MAX_WIDTH} {MAX_WIDTH_LABEL}</p>
    <p>{MAX_HEIGHT} {MAX_HEIGHT_LABEL}</p>
</fieldset>
{SAVE}
{END_FORM}
