{START_FORM}

{PAGETEXT_LABEL}:<br />
{PAGETEXT}<br /><br />

{COMMENT_LABEL}:<br />
{COMMENT}<br /><br />

{SAVE} {PREVIEW} {CANCEL}
{END_FORM}

<!-- BEGIN PREVIEW_PAGE -->
<hr />
{PREVIEW_PAGE}
<!-- END PREVIEW_PAGE -->