<?php

/**
 * Information originally pulled from http://wwp.greenwichmeantime.com/info/timezone.htm
 */

$timezones = array(
array ('id' => -12, 'codes' => array('IDLW: International Date Line West'), 'city' => NULL),
array ('id' => -11, 'codes' => array('NT: Nome'), 'city' => NULL),
array ('id' => -10, 'codes' => array('AHST: Alaska-Hawaii Standard',
                                                        'CAT: Central Alaska',
                                                        'HST: Hawaii Standard'), 'city' => NULL),
array ('id' => -9,  'codes' => array('YST:  Yukon Standard'), 'city' => NULL),
array ('id' => -8,  'codes' => array('PST: Pacific Standard'), 'city' => array('Los Angeles, CA, USA')),
array ('id' => -7,  'codes' => array('MST: Mountain Standard'), 'city' => NULL),
array ('id' => -6,  'codes' => array('CST: Central Standard'), 'city' => array('Mexico City, Mexico',
                                                                                                  'Saskatchewan, Canada')),
array ('id' => -5,  'codes' => array('EST: Eastern Standard'), 'city' => array('Bogota',
                                                                                                  'Lima, Peru',
                                                                                                  'New York, NY, USA')),
array ('id' => -4,  'codes' => array('AST: Atlantic Standard'), 'city' => array('Caracas',
                                                                                                   'La Paz')),
array ('id' => -3.5,'codes' => NULL, 'city' => array('Newfoundland')),
array ('id' => -3,  'codes' => NULL, 'city' => array('Brasilia, Brazil',
                                                                        'Buenos Aires, Argentina',
                                                                        'Georgetown, Guyana')),
array ('id' => -2,  'codes' => array('AT: Azores'), 'city' => NULL),
array ('id' => -1,  'codes' => array('WAT: West Africa'), 'city' => array('Azores, Cape Verde Islands')),
array ('id' =>  0,  'codes' => array('GMT: Greenwich Mean',
                                                        'UT: Universal',
                                                        'UTC: Universal Co-ordinated',
                                                        'WET: Western European'), 'city' => array('London, England',
                                                                                                  'Dublin, Ireland',
                                                                                                  'Edinburgh, Scotland',
                                                                                                  'Lisbon, Portugal',
                                                                                                  'Reykjavik, Iceland',
                                                                                                  'Casablanca, Morocco')),
array ('id' =>  1,  'codes' => array('CET: Central European'), 'city' => array('Paris, France',
                                                                                                  'Berlin, Germany',
                                                                                                  'Amsterdam, The Netherlands',
                                                                                                  'Brussels, Belgium',
                                                                                                  'Vienna, Austria',
                                                                                                  'Madrid, Spain',
                                                                                                  'Rome, Italy',
                                                                                                  'Bern, Switzerland',
                                                                                                  'Stockholm, Sweden',
                                                                                                  'Oslo, Norway')),
array ('id' =>  2,  'codes' => array('EET: Eastern European'), 'city' => array('Athens, Greece',
                                                                                                  'Helsinki, Finland',
                                                                                                  'Istanbul, Turkey',
                                                                                                  'Jerusalem, Israel',
                                                                                                  'Harare, Zimbabwe')),
array ('id' =>  3,  'codes' => array('BT: Baghdad'), 'city' => array('Kuwait',
                                                                                        'Nairobi, Kenya',
                                                                                        'Riyadh, Saudi Arabia',
                                                                                        'Moscow, Russia')),
array ('id' =>  3.5,'codes' => NULL, 'city' => array('Tehran, Iran')),
array ('id' =>  4,  'codes' => NULL, 'city' => array('Abu Dhabi, UAE',
                                                                        'Muscat',
                                                                        'Tblisi',
                                                                        'Volgograd',
                                                                        'Kabul')),
array ('id' =>  4.5,'codes' => NULL, 'city' => array('Afghanistan')),
array ('id' =>  5,  'codes' => NULL, 'city' => NULL),
array ('id' =>  5.5,'codes' => NULL, 'city' => array('India')),
array ('id' =>  6,  'codes' => NULL, 'city' => NULL),
array ('id' =>  6.5,'codes' => NULL, 'city' => array('Cocos Islands')),
array ('id' =>  7,  'codes' => NULL, 'city' => NULL),
array ('id' =>  8,  'codes' => array('CCT: China Coast'), 'city' => NULL),
array ('id' =>  9,  'codes' => array('JST: Japan Standard'), 'city' => NULL),
array ('id' =>  9.5,'codes' => array('Australia Central Standard'), 'city' => array('Darwin, Australia',
                                                                                                       'Adelaide, Australia')),
array ('id' =>  10, 'codes' => array('GST: Guam Standard'), 'city' => NULL),
array ('id' =>  10.5,'codes' => NULL, 'city' => array('Lord Howe Island')),
array ('id' =>  11, 'codes' => NULL, 'city' => NULL),
array ('id' =>  11.5,'codes' => NULL, 'city' => array('Norfolk Island')),
array ('id' =>  12, 'codes' => array('IDLE: International Date Line East',
                                                        'NZST: New Zealand Standard'), 'city' => array('Wellington, New Zealand',
                                                                                                       'Fiji',
                                                                                                       'Marshall Islands')),
array ('id' =>  13, 'codes' => NULL, 'city' => array('Rawaki Islands: Enderbury',
                                                                        'Kiribati')),
array ('id' =>  14, 'codes' => NULL, 'city' => array('Line Islands: Kiritibati')),
);

?>