{START_FORM}
{EDIT_SLOT}
<table cellpadding="4" width="100%">
  <tr>
    <td><strong>{TITLE_LABEL}</strong></td><td>{TITLE}</td>
  </tr>
  <tr>
    <td><strong>{DESCRIPTION_LABEL}</strong></td><td>{DESCRIPTION}</td>
  </tr>
  <tr>
    <td><strong>{CONTACT_EMAIL_LABEL}</strong></td><td>{CONTACT_EMAIL}</td>
  </tr>
  <tr>
    <td><strong>{END_TIME_LABEL}</strong></td><td>{END_TIME}{ET_JS}</td>
  </tr>
  <tr>
    <td><strong>{MULTIPLE_LABEL}</strong></td><td>{MULTIPLE}</td>
  </tr>
</table>
{SUBMIT}
{END_FORM}
