<p>{LABEL_LABEL} {LABEL_INPUT}</p>
<p>{SIZE_LABEL} {SIZE_INPUT} &nbsp; {MAXSIZE_LABEL} {MAXSIZE_INPUT}</p>
<p>{VALUE_LABEL} {VALUE_INPUT}</p>
<p>{REQUIRE_LABEL} {REQUIRE_INPUT}</p>
<p>{SORT_LABEL} {SORT_INPUT}</p>
<p>{ACTIVE_LABEL} {ACTIVE_INPUT}<br />
{LIST_LABEL} {LIST_INPUT}<br />
{PRIVATE_LABEL} {PRIVATE_INPUT}</p>
<p>{NEXT_BUTTON}</p>
