<p>{LABEL_LABEL} {LABEL_INPUT}</p>
<p>{OPTIONS_LABEL} {OPTIONS_INPUT}</p>
<!-- BEGIN OPTION_SET -->
{OPTION_SET_LABEL}<br />
{OPTION_SET_INPUT}<br /><br />
<!-- END OPTION_SET -->
<p>{REQUIRE_LABEL} {REQUIRE_INPUT}</p>
<p>{SORT_LABEL} {SORT_INPUT}</p>
<p>
    {ACTIVE_LABEL} {ACTIVE_INPUT}<br />
    {LIST_LABEL} {LIST_INPUT}<br />
    {SEARCH_LABEL} {SEARCH_INPUT}<br />
    {PRIVATE_LABEL} {PRIVATE_INPUT}
</p>
<p>{NEXT_BUTTON}</p>
