<p>{LABEL_LABEL} {LABEL_INPUT}</p>
<p>{COLS_LABEL} {COLS_INPUT} &nbsp; {ROWS_LABEL} {ROWS_INPUT}</p>
<p>{VALUE_LABEL} {VALUE_INPUT}</p>
<p>{REQUIRE_LABEL} {REQUIRE_INPUT}</p>
<p>{SORT_LABEL} {SORT_INPUT}</p>
<p>
    {ACTIVE_LABEL} {ACTIVE_INPUT}<br />
    {LIST_LABEL} {LIST_INPUT}<br />
    {SEARCH_LABEL} {SEARCH_INPUT}
</p>
<p>{NEXT_BUTTON}</p>
