{START_FORM}
<!-- BEGIN FORM_INFO -->
{FORM_INFORMATION}
<br />
<!-- END FORM_INFO -->
<div class="smalltext"><b>{PHAT_FORMNAME_LABEL}:</b><br />
{PHAT_FORMNAME}<br />
<br />
<b>{PHAT_FORMBLURB0_LABEL}:</b><br />
{PHAT_FORMBLURB0}<br />
<br />
<b>{PHAT_FORMBLURB1_LABEL}:</b><br />
{PHAT_FORMBLURB1}<br />
<br />
<b>{PHAT_POSTPROCESS_LABEL}:</b>{POSTPROCESS_HELP}<br />
{PHAT_POSTPROCESS}<br />
<br />
<b>{PHAT_FORMEMAILS_LABEL}:</b><br />
{PHAT_FORMEMAILS}<br />
<br />
{PHAT_FORMPAGELIMIT} {PHAT_FORMPAGELIMIT_LABEL}.<br />
{PHAT_FORMEDITDATA} {PHAT_FORMEDITDATA_LABEL}.<br />
{PHAT_FORMMULTISUBMIT} {PHAT_FORMMULTISUBMIT_LABEL}.<br />
{PHAT_FORMANONYMOUS} {PHAT_FORMANONYMOUS_LABEL}.<br />
{PHAT_FORMSHOWELEMENTNUMBERS} {PHAT_FORMSHOWELEMENTNUMBERS_LABEL}.<br />
{PHAT_FORMSHOWPAGENUMBERS} {PHAT_FORMSHOWPAGENUMBERS_LABEL}.<br />
{PHAT_FORMHIDDEN} {PHAT_FORMHIDDEN_LABEL}.<br />
</div>
<br />
{PHAT_SAVESETTINGS} {PHAT_EDITELEMENTS} {END_FORM}
