{START_FORM}
<div class="box-title"><h1>{TITLE}</h1></div>
<table class="form-table">
  <tr>
    <td>{ORDER_LABEL}</td>
    <td>{ORDER}</td>
  </tr>
  <tr>
    <td>{CAPTCHA_LABEL}</td>
    <td>{CAPTCHA}</td>
  </tr>
  <tr>
    <td>{ALLOW_SIGNATURES_LABEL}</td>
    <td>{ALLOW_SIGNATURES}</td>
  </tr>
  <tr>
    <td>{ALLOW_IMAGE_SIGNATURES_LABEL}</td>
    <td>{ALLOW_IMAGE_SIGNATURES}</td>
  </tr>
  <tr>
    <td>{ALLOW_AVATARS_LABEL}</td>
    <td>{ALLOW_AVATARS}</td>
  </tr>
  <tr>
    <td>{LOCAL_AVATARS_LABEL}</td>
    <td>{LOCAL_AVATARS}</td>
  </tr>
  <tr>
    <td>{ANONYMOUS_NAMING_LABEL}</td>
    <td>{ANONYMOUS_NAMING}</td>
  </tr>
  <tr>
    <td>{RECENT_COMMENTS_LABEL}</td>
    <td>{RECENT_COMMENTS}</td>
  </tr>
  <tr>
    <td>{DEFAULT_APPROVAL_LABEL}</td>
    <td>{DEFAULT_APPROVAL}</td>
  </tr>
 </table>
{SUBMIT}
{END_FORM}
