{START_FORM}
<fieldset>
    <legend><strong>{SETTINGS_LABEL}</strong></legend>
    <p>{ENABLE_ELECTIONS} {ENABLE_ELECTIONS_LABEL}</p>
    <p>{ENABLE_SIDEBOX} {ENABLE_SIDEBOX_LABEL}</p>
    <p>{SIDEBOX_HOMEONLY} {SIDEBOX_HOMEONLY_LABEL}</p>
    <p>{TITLE_LABEL}<br />{TITLE}</p>
    <p>{SIDEBOX_TEXT_LABEL}<br />{SIDEBOX_TEXT}</p>
    <p>{ENABLE_IMAGES} {ENABLE_IMAGES_LABEL}</p>
    <p>{MAX_WIDTH} {MAX_WIDTH_LABEL}</p>
    <p>{MAX_HEIGHT} {MAX_HEIGHT_LABEL}</p>
    <p>{EXPIRY_INTERVAL} {EXPIRY_INTERVAL_LABEL}</p>
</fieldset>
{SAVE}
{END_FORM}
