{START_FORM}
<fieldset><legend><strong>{DETAILS_LABEL}</strong></legend>
<p>{TITLE} {TITLE_LABEL}</p>
<p>{DESCRIPTION_LABEL}<br />
{DESCRIPTION}</p>
<p>{FILE_MANAGER}</p>
<p>{SHOW_IN_BLOCK} {SHOW_IN_BLOCK_LABEL}<br />
{PUBVIEW} {PUBVIEW_LABEL}<br />
{PUBVOTE} {PUBVOTE_LABEL}</p>
<p>{VOTEGROUPS_LABEL}<br />
{VOTEGROUPS}</p>
<p>{MINCHOICE} {MINCHOICE_LABEL}<br />
{MAXCHOICE} {MAXCHOICE_LABEL}<br />
{RANKING} {RANKING_LABEL}</p>
<p>{OPENING} {OPENING_CAL} {OPENING_LABEL} <span class="smaller">{EXAMPLE}</span><br />
{CLOSING} {CLOSING_CAL} {CLOSING_LABEL} <span class="smaller">{EXAMPLE}</span>
</p>
<p>{CUSTOMFIELDS_TEXT}<br />
<span class="smalltext">{CUSTOMFIELDS_NOTE}</span><br />
{CUSTOM1LABEL}{CUSTOM1LABEL_LABEL}<br />
{CUSTOM2LABEL}{CUSTOM2LABEL_LABEL}<br />
{CUSTOM3LABEL}{CUSTOM3LABEL_LABEL}<br />
{CUSTOM4LABEL}{CUSTOM4LABEL_LABEL}<br />
</p>
</fieldset>
{SUBMIT} {END_FORM}
