{START_FORM}
<p>{USERNAME_LABEL}<br />{USERNAME}</p>
<fieldset><legend>{FILTER_LEGEND}</legend>
<p>{FILTER_TYPE_1} {FILTER_TYPE_1_LABEL}</p>
<p>{FILTER_TYPE_2} {FILTER_TYPE_2_LABEL}<br />
{LAST_NAME_FILTER}<br />{LAST_NAME_FILTER_LABEL}</p>
<p>{FILTER_TYPE_3} {FILTER_TYPE_3_LABEL}<br />
<strong>{REASONS_LABEL}</strong> {REASONS}

</p>
</fieldset>
{END_FORM}