<h1>AddThis Settings</h1>

<p>
{START_FORM}
{ENABLED_CHECK_1} {ENABLED_CHECK_1_LABEL}<br />
{ENABLED_CHECK_2} {ENABLED_CHECK_2_LABEL}<br />
{ENABLED_CHECK_3} {ENABLED_CHECK_3_LABEL}<br />
{ENABLED_CHECK_4} {ENABLED_CHECK_4_LABEL}

<br /><br />
{SUBMIT}
{END_FORM}
</p>
