{START_FORM}
<p>{MENU}</p>
<p>{PURGE}</p>
<p>{DEFAULT_SLOCATION_LABEL} {DEFAULT_SLOCATION}</p>
<p><strong>{DISTANCE_LABEL}</strong><br />
{MILES_OR_KILOMETERS_1} {MILES_OR_KILOMETERS_1_LABEL}<br />
{MILES_OR_KILOMETERS_2} {MILES_OR_KILOMETERS_2_LABEL}</p>
<p>{CARPOOL} {CARPOOL_LABEL}</p>
<p>{DEFAULT_DESTINATION_LABEL} {DEFAULT_DESTINATION}</p>
<p>{SUBMIT}</p>
{END_FORM}
