{START_FORM}
<fieldset><legend><strong>{GENERAL_GROUP_LABEL}</strong></legend>
<p>{ENABLE_SIDEBOX} {ENABLE_SIDEBOX_LABEL}<br />
{SIDEBOX_HOMEONLY} {SIDEBOX_HOMEONLY_LABEL}</p>
<p>{ENABLE_FILES} {ENABLE_FILES_LABEL}<br />
{MAX_WIDTH} {MAX_WIDTH_LABEL}<br />
{MAX_HEIGHT} {MAX_HEIGHT_LABEL}</p>
<p>{USE_INVENTORY} {USE_INVENTORY_LABEL}</p>
<p>{ADMIN_EMAIL} {ADMIN_EMAIL_LABEL}</p>
<p>{PAY_METHODS}{PAY_METHODS_LABEL}<br />
<strong>{PAY_METHODS_NOTE_TITLE}</strong> {PAY_METHODS_NOTE}</p>
<p>{SECURE_CHECKOUT} {SECURE_CHECKOUT_LABEL}<br />
{SECURE_URL_LABEL}<br />
{SECURE_URL}</p>
</fieldset>
<fieldset><legend><strong>{TEXT_GROUP_LABEL}</strong></legend>
<p>{MOD_TITLE_LABEL}<br />
{MOD_TITLE}</p>
<p>{USE_BREADCRUMB} {USE_BREADCRUMB_LABEL}</p>
<p>{SIDEBOX_TEXT_LABEL}<br />
{SIDEBOX_TEXT}</p>
<p>{CHECKOUT_INST_LABEL}<br />
{CHECKOUT_INST}</p>
<p>{ORDER_MESSAGE_LABEL}<br />
{ORDER_MESSAGE}</p>
</fieldset>
<fieldset><legend><strong>{CURRENCY_GROUP_LABEL}</strong></legend>
<p>{CURRENCY} {CURRENCY_LABEL}</p>
<p>{DISPLAY_CURRENCY} {DISPLAY_CURRENCY_LABEL}</p>
<p>{CURRENCY_SYMBOL} {CURRENCY_SYMBOL_LABEL}</p>
<p>{CURR_SYMBOL_POS} {CURR_SYMBOL_POS_LABEL}</p>
<p>{WEIGHT_UNIT} {WEIGHT_UNIT_LABEL}</p>
</fieldset>
<fieldset><legend><strong>{SHIPPING_GROUP_LABEL}</strong></legend>
<p>{SHIPPING_CALCULATION} {SHIPPING_CALCULATION_LABEL}</p>
<p>{SHIPPING_FLAT}{SHIPPING_FLAT_LABEL}</p>
<p>{SHIPPING_PERCENT}{SHIPPING_PERCENT_LABEL}</p>
<p>{SHIPPING_MINIMUM} {SHIPPING_MINIMUM_LABEL}</p>
<p>{SHIPPING_MAXIMUM} {SHIPPING_MAXIMUM_LABEL}</p>
{SAVE} {END_FORM}