export const Departments = [
  {title: 'Career Development Center', url: '//careers.appstate.edu'},
  {title: 'Child Development', url: '//childdevelopment.appstate.edu/'},
  {title: 'Counseling & Psychological Services', url: '//counseling.appstate.edu/'},
  {title: 'Office of the Dean of Students', url: '//deanofstudents.appstate.edu'},
  {title: 'Electronic Student Services', url: '//ess.appstate.edu'},
  {title: 'Multicultural Student Development', url: '//multicultural.appstate.edu'},
  {title: 'Parent and Family Services', url: '//parents.appstate.edu'},
  {title: 'Off-Campus Student Services', url: '//offcampus.appstate.edu'},
  {title: 'Student Health Services', url: '//healthservices.appstate.edu'},
  {title: 'Student Legal Services', url: '//legalclinic.appstate.edu'},
  {title: 'Staff Development and Strategic Initiatives', url: '//studentaffairs.appstate.edu'},
  {title: 'Student Conduct', url: '//studentconduct.appstate.edu'},
  {title: 'Student Engagement and Leadership', url: '//engageandlead.appstate.edu'},
  {title: 'University Housing', url: '//housing.appstate.edu'},
  {title: 'University Recreation', url: '//urec.appstate.edu'},
  {title: 'Wellness & Prevention Services', url: '//wellness.appstate.edu'},
]
