{START_FORM}
<table class="form-table">
  <tr>
    <td>{TITLE_LABEL}</span></td>
    <td>{TITLE}</td>
  </tr>
  <tr>
    <td>{ENTRY_LABEL}</span></td>
    <td>{ENTRY}</td>
  </tr>
  <tr>
    <td>{ALLOW_COMMENTS_LABEL}</td>
    <td>{ALLOW_COMMENTS}</td>
  </tr>
  <tr>
    <td>{ALLOW_ANON_LABEL}</td>
    <td>{ALLOW_ANON}</td>
  </tr>
</table>
{SUBMIT}
{END_FORM}
