{START_FORM}
<table class="form-table" widht="99%">
   <tr>
      <td>{BLOG_LIMIT_LABEL}
      </td>
      <td>{BLOG_LIMIT}
      </td>
   </tr>
   <tr>
      <td>{PAST_ENTRIES_LABEL}<br /><span class="smaller">{PAST_NOTE}</span>
      </td>
      <td>{PAST_ENTRIES}
      </td>
   </tr>
   <tr>
      <td>{ALLOW_COMMENTS_LABEL}
      </td>
      <td>{ALLOW_COMMENTS}
      </td>
   </tr>
   <tr>
      <td>{HOME_PAGE_DISPLAY_LABEL}
      </td>
      <td>{HOME_PAGE_DISPLAY}
      </td>
   </tr>
</table>
{SUBMIT}
{END_FORM}
