{START_FORM}
<p>{STAFF_SEE_REPORTS} {STAFF_SEE_REPORTS_LABEL}</p>
<p>{UNASSIGNED_SEEN} {UNASSIGNED_SEEN_LABEL}</p>
<p>{FRONT_PAGE} {FRONT_PAGE_LABEL}</p>
<p>{COLLAPSE_SIGNIN} {COLLAPSE_SIGNIN_LABEL}</p>
<p>{SENDBACK} {SENDBACK_LABEL}</p>
<p>{EMAIL} {EMAIL_LABEL}</p>
<!--<p>{GENDER} {GENDER_LABEL}</p>-->
<P>{BIRTHDATE} {BIRTHDATE_LABEL}</p>
<p>{ASSIGN_REFRESH_LABEL} {ASSIGN_REFRESH}</p>
<p>{WAITING_REFRESH_LABEL} {WAITING_REFRESH}</p>
{SUBMIT} {END_FORM}
