{START_FORM}
<!-- BEGIN TRACKER_EDIT -->
<h2>Editing: {TRACKER_TYPE}</h2>
<!-- END TRACKER_EDIT -->
<!-- BEGIN TRACKER_NEW -->
<h2>New Tracker</h2>
<p>{TRACKER_LABEL}<br />{TRACKER}</p>
<!-- END TRACKER_NEW -->
<p>{NAME_LABEL}<br />{NAME}</p>
<p>{ACTIVE} {ACTIVE_LABEL}</p>
<p>{DISABLE_IF_LOGGED} {DISABLE_IF_LOGGED_LABEL}</p>
<p>{ACCOUNT_LABEL}<br />{ACCOUNT}</p>
{SUBMIT}
{END_FORM}
