<?php
  /**
   * @version $Id$
   * @author Matthew McNaney <mcnaney at gmail dot com>
   */
$icon_list = array('application/asx'          => 'video.png',
                   'application/futuresplash' => 'flash_icon.png',
                   'application/pdf'          => 'pdf.png',
                   'application/vnd.ms-excel' => 'spreadsheet.png',
                   'application/vnd.ms-powerpoint' => 'powerpoint.png',
                   'application/x-tar'        => 'package.png',
                   'application/x-gtar'       => 'package.png',
                   'application/x-gzip'       => 'package.png',
                   'application/x-javascript' => 'document.png',
                   'application/x-shockwave-flash' => 'flash_icon.png',
                   'application/x-ustar'      => 'package.png',
                   'text/html'                => 'html.png',
                   'application/x-bzip2'      => 'package.png',
                   'application/x-gzip'       => 'package.png',
                   'application/zip'          => 'package.png',
                   'audio/basic'              => 'audio.png',
                   'audio/midi'               => 'audio.png',
                   'audio/mpeg'               => 'audio.png',
                   'audio/vnd.rn-realaudio'   => 'realplayer.png',
                   'audio/x-pn-realaudio'     => 'realplayer.png',
                   'audio/x-pn-realaudio-plugin' => 'realplayer.png',
                   'audio/x-wav'              => 'audio.png',
                   'image/bmp'                => 'document.png',
                   'image/gif'                => 'document.png',
                   'image/jpeg'               => 'document.png',
                   'image/png'                => 'document.png',
                   'image/tiff'               => 'document.png',
                   'text/css'                 => 'html.png',
                   'text/html'                => 'html.png',
                   'text/plain'               => 'text.png',
                   'text/x-sgml'              => 'html.png',
                   'text/xml'                 => 'document.png',
                   'text/xsl'                 => 'document.png',
                   'application/rtf'          => 'text.png',
                   'text/richtext'            => 'text.png',
                   'video/mpeg'               => 'video.png',
                   'video/quicktime'          => 'video.png' ,
                   'video/vnd.rn-realvideo'   => 'video.png' ,
                   'video/vnd.vivo'           => 'video.png' ,
                   'video/x-bamba'            => 'video.png' ,
                   'video/x-ms-asf'           => 'video.png' ,
                   'video/x-ms'               => 'video.png' ,
                   'video/x-qmsys'            => 'video.png' ,
                   'video/x-sgi-movie'        => 'video.png' ,
                   'video/x-tango'            => 'video.png' ,
                   'video/x-vif'              => 'video.png');

?>
