{START_FORM}
<fieldset><legend>{MOD_REWRITE_LABEL}</legend>
{REWRITE_ENGINE} {REWRITE_ENGINE_LABEL}<br />
{SHORTCUTS_ENABLED} {SHORTCUTS_ENABLED_LABEL}<br />
{ALLOW_DENY_ENABLED} {ALLOW_DENY_ENABLED_LABEL}<br />
</fieldset>
<fieldset><legend>{HTACCESS_LABEL}</legend>
{ALLOW_FILE_UPDATE} {ALLOW_FILE_UPDATE_LABEL}</fieldset>
{SUBMIT} {END_FORM}
