<div id="slot-no">{TITLE}</div>
{START_FORM}
<p>{BACKGROUND_IMAGE_LABEL}<br />
{BACKGROUND_IMAGE} {pic_dimensions}</p>
<p>{THUMBNAIL_IMAGE_LABEL}<br />
{THUMBNAIL_IMAGE} {thumb_dimensions}</p>
<p>{THUMBNAIL_TEXT_LABEL}<br />{THUMBNAIL_TEXT}</p>
<p>{FEATURE_TEXT_LABEL}<br />
{FEATURE_TEXT}
</p>
<p>{DESTINATION_URL_LABEL}{DESTINATION_URL}</p>
<p>{FEATURE_X_LABEL} {FEATURE_X} {FEATURE_Y_LABEL} {FEATURE_Y}</p>
{ADD} {DELETE}
{END_FORM}