{START_FORM}
<table class="form-table" width="100%">
  <tr>
    <td>{PROFILE_TYPE_LABEL}</td>
    <td>{PROFILE_TYPE}</td>
  </tr>
  <tr>
    <td>{FIRSTNAME_LABEL}</td>
    <td>{FIRSTNAME}</td>
  </tr>
  <tr>
    <td>{LASTNAME_LABEL}</td>
    <td>{LASTNAME}</td>
  </tr>
  <tr>
    <td>{CAPTION_LABEL}</td>
    <td>{CAPTION}</td>
  </tr>
  <tr>
    <td>{FULLSTORY_LABEL}</td>
    <td>{FULLSTORY}</td>
  </tr>
  <tr>
    <td>{EMAIL_LABEL}</td>
    <td>{EMAIL}</td>
  </tr>
  <tr>
    <td>{WEBSITE_LABEL}</td>
    <td>{WEBSITE}</td>
  </tr>
  <tr>
    <td>{KEYWORDS_LABEL}</td>
    <td>{KEYWORDS}</td>
  </tr>
  <tr>
    <td>{KEYWORDS_LABEL}</td>
    <td>
      <table>
        <tr>
          <td><strong>{PHOTO_LARGE_LABEL}</strong><br />{PHOTO_LARGE}</td>
          <td><strong>{PHOTO_MEDIUM_LABEL}</strong><br />{PHOTO_MEDIUM}</td>
          <td><strong>{PHOTO_SMALL_LABEL}</strong><br />{PHOTO_SMALL}</td>
        </tr>
      </table>
    </td>
  </tr>
</table>
{SUBMIT}
{END_FORM}
